name: Archive

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '21'

    - name: Install dependencies
      run: npm ci

    - name: Get version number
      id: version
      run: echo "::set-output name=version::$(node -p "require('./src/manifest.json').version")"

    - name: Archive code
      run: |
        mkdir release
        cp -r src/* release/
        zip -r calm-ntp-release-${{ steps.version.outputs.version }}.zip release/
